name: CI for Unit Tests

on:
  push:
    branches:
      - branchAutoTest2
  pull_request:
    branches:
      - branchAutoTest2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C++
        uses: actions/setup-cpp@v2
        with:
          compiler: gcc

      - name: Install dependencies
        run: sudo apt-get install -y libgtest-dev cmake

      - name: Build the project
        run: |
          autoreconf -i
          ./configure
          make

      - name: Run tests
        run: ./program

