name: C++ Build and Tarball Distribution

on:
  push:
    branches:
      - main
      - branchAutomake
  pull_request:
    branches:
      - main
      - branchAutomake

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up C++ environment
        run: sudo apt-get install g++ make automake autoconf dephelper

      - name: Build the project using automake
        run: |
          ./autogen.sh
          ./configure
          make

       - name: Create Debian package
        run: |
          debuild -us -uc

      - name: Upload .deb package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: devopss-deb-package
          path: ../*.deb
