name: Build and Test C++ Project

on:
  push:
    branches:
      - main
      - branchAutoTest
  pull_request:
    branches:
      - main
      - branchAutoTest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up C++ environment
        run: sudo apt-get install g++ make automake autoconf debhelper libgtest-dev

      - name: Build the project using automake
        run: |
          ./autogen.sh
          ./configure
          make

      - name: Run unit tests
        run: |
          make check
