name: CI for Unit Tests

on:
  push:
    branches:
      - branchAutoTest
  pull_request:
    branches:
      - branchAutoTest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C++ Build Environment
        run: sudo apt update && sudo apt install -y g++

      - name: Install dependencies
        run: sudo apt-get install -y libgtest-dev cmake

      - name: Build the project
        run: |
          autoreconf -i
          ./configure
          make

      - name: Run tests
        run: ./program

