name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - branchHTTPservMutli
  pull_request:
    branches:
      - branchHTTPservMutli

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up QEMU for cross-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ vars.DOCKER_TOKEN }}

      # Build and push multi-arch Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/my-http-server:latest
            ${{ vars.DOCKER_USERNAME }}/my-http-server:${{ github.sha }}
          platforms: linux/amd64,linux/arm64


